
version: '2'
services:
  groups:
    image: groups:0.0.1
    container_name: groups
    depends_on:
    - mariadb
    environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://groups:3306/mydb?useUnicode=true&characterEncoding=utf8&useSSL=false
    ports:
    - 8080:8080

  mariadb:
    image: mariadb:latest
    container_name: groupsdb
    volumes:
    - /home/docker/volumes/myapp/mysql/:/var/lib/mysql/
    environment:
    - MYSQL_ROOT_PASSWORD=mysql
    - MYSQL_DATABASE=groups
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=mysql
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8
