version: "2"
services:
  docker-mysql:
    image: wangxian/alpine-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=groups
      - MYSQL_PASSWORD=mysql
  spring-docker-service:
    image: spring-docker-service
    build:
      context: ./spring/
      dockerfile: Dockerfile.spring
    depends_on:
      - docker-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=mysql
      - DATABASE_NAME=groups
      - DATABASE_PORT=3306
  angular-docker-service:
    image: angular-docker-service
    build:
      context: ./angular/
      dockerfile: Dockerfile.angular
    ports:
      - 80:80
