version: "2"
services:
  docker-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=root
  spring-docker-service:
    image: spring-docker-service
    build:
      context: ./aot-angular
      dockerfile: ./Dockerfile.angular
    depends_on:
      - docker-mysql
    ports:
      - 8080:8080
    environment:
      - CATALINA_OPTS=-Dspring.profiles.active=container
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=test
      - DATABASE_PORT=3306
  angular-docker-service:
    image: angular-docker-service
    build:
      context: ./groups
      dockerfile: ./Dockerfile.spring
    ports:
      - 80:80
