
version: '2'
services:
  groups:
    image: sokeno/groups:0.0.1
    container_name: groups
    depends_on:
    - mariadb
    environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://studentstoragedb:3306/studentstorage?useUnicode=true&characterEncoding=utf8&useSSL=false
    ports:
    - 8081:8081

  crfrontend:
    image: sokeno/aot-angular:0.0.1
    container_name: aot-angular
    ports:
    - 4200:80

  mariadb:
    image: mariadb
    container_name: groupsdb
    ports:
    - "3307:3306"
    volumes:
    - /home/docker/volumes/myapp/mysql/:/var/lib/mysql/
    environment:
    - MYSQL_ROOT_PASSWORD=mysql
    - MYSQL_DATABASE=groups
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=mysql
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8